spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 40
      minimum-idle: 10
      idle-timeout: 30000
      pool-name: PerfUrl-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  web:
    resources:
      static-locations: classpath:/static/,file:/app/static/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration-time: ${JWT_EXPIRATION_TIME}

app:
  base-url: https://perfurl.com